# 빅콘테스트 퓨처스리그 : KBO 정규시즌 팀별 승률, 타율, 방어율 예측

2020.08.11 화요일 김채형

## Preprocessing

### 파생변수 생성하기 - DER

**공식** : DER = (타석 - 안타 - 삼진 - 볼넷 - 몸에맞는볼 - 에러출루) + (타석 - 홈런 - 삼진 - 볼넷 - 몸에맞는공)

**해석** : '인플레이 타구를 수비수들이 아웃으로 잘 잡아냈는가?'를 나타내는 지표

In [1]:
import pandas as pd

In [2]:
data = pd.read_csv('../../data/pitcher_all.csv', index_col=0)
data

,year,month,T_ID,P_ID,START_CK,RELIEF_CK,CG_CK,HOLD,INN2,BF,...,WLS_D,WLS_L,WLS_ND,WLS_S,WLS_W,KBB,AVG,OBP,SLG,OPS
0,2016,4,HH,60757,0,8,0,0,30,195,...,0,0,8,0,0,NaN,0.372093,0.437500,0.581395,1.018895
1,2016,4,HH,60764,1,1,0,0,2,48,...,0,1,1,0,0,1.800,0.500000,0.875000,0.500000,1.375000
2,2016,4,HH,60768,2,0,0,0,24,123,...,0,2,0,0,0,0.000,0.258065,0.323529,0.483871,0.807400
3,2016,4,HH,63791,0,10,0,0,32,181,...,0,0,10,0,0,1.000,0.225000,0.311111,0.275000,0.586111
4,2016,4,HH,65764,3,1,0,0,22,192,...,0,3,1,0,0,2.200,0.428571,0.534884,0.657143,1.192027
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5299,2020,7,WO,68341,0,9,0,3,24,152,...,0,2,7,0,0,1.400,0.200000,0.368421,0.300000,0.668421
5300,2020,7,WO,69343,3,0,0,0,60,293,...,0,0,1,0,2,1.375,0.293333,0.311688,0.373333,0.685022
5301,2020,7,WO,69360,1,0,0,0,2,24,...,0,0,1,0,0,11.000,0.600000,0.714286,0.800000,1.514286
5302,2020,7,WO,69399,0,2,0,0,10,70,...,0,0,2,0,0,0.000,0.529412,0.550000,0.588235,1.138235
5303,2020,7,WO,76430,0,7,0,1,19,96,...,0,0,6,0,1,0.000,0.173913,0.240000,0.217391,0.457391

In [3]:
df = data.copy()

In [4]:
df['DER'] = (df['PA'] - df['HIT'] - df['KK'] - df['BB'] - df['HP'] - df['ERR']) + (df['PA'] - df['HR'] - df['KK'] - df['BB'] - df['HP'])

In [5]:
# 기존 pitcher_all.csv 파일 파생변수 추가하여 업데이트
df.to_csv('../../data/pitcher_all.csv')