## 빅콘테스트 퓨쳐스리그: KBO 정규시즌 팀별 승률, 타율, 평균방어율 예측

### 2020년 7월 19일 이후 인플레이 타수 예측

In [1]:
import numpy as np
import pandas as pd

In [2]:
data = pd.read_csv("C:/Users/njj06/Desktop/prediction.csv")

In [3]:
df1 = data.copy()

In [4]:
data2 = pd.read_csv("C:/Users/njj06/Desktop/ESC_summer/Baseball_ChilliShrimp/data/batter_tidy.csv")

In [5]:
df2 = data2.copy()

In [6]:
df1 = df1.groupby('P_ID').sum()

In [7]:
id = list(df1.index)

In [8]:
df1 = data.copy()

In [9]:
df1 = df1.groupby(['P_ID', 'year', 'month']).sum()

In [10]:
df1

                   PA
P_ID  year month
50054 2020 7        7
           8       27
           9       32
           10      29
50066 2020 7        0
           8        0
           9        0
           10       0
50150 2020 7        8
           8       13
           9       14
           10      11
50165 2020 7       60
           8       93
           9       95
           10      77
50202 2020 7        4
           8        4
           9        1
           10       1
50204 2020 7        0
           8        1
           9        1
           10       1
50208 2020 7        1
           8        2
           9        2
           10       2
50293 2020 7        5
           8       19
...               ...
79293 2020 9        0
           10       0
79334 2020 7        1
           8        3
           9        3
           10       3
79365 2020 7       50
           8       90
           9       91
           10      61
79402 2020 7       54
           8      111
           9      105
           10      82
79456 2020 7       40
           8       63
           9       58
           10      39
79545 2020 7        0
           8        0
           9        0
           10       0
79608 2020 7       46
           8       86
           9       92
           10      82
79705 2020 7        0
           8        1
           9        2
           10       1

[1172 rows x 1 columns]

In [11]:
df2 = df2.loc[df2['year']==2020]

In [12]:
df2 = df2.groupby(['P_ID']).sum()

In [13]:
df2

,year,month,PA,AB,RBI,RUN,HIT,H2,H3,HR,...,VS_T_ID_LG,VS_T_ID_LT,VS_T_ID_NC,VS_T_ID_OB,VS_T_ID_SK,VS_T_ID_SS,VS_T_ID_WO,BAT_ORDER,HOME,AWAY
P_ID,,,,,,,,,,,,,,,,,,,,,
50054,4040,13,53,47,0,6,12,3,0,0,...,2,4,6,2,3,4,1,15,12,16
50066,6060,18,27,25,3,2,6,2,0,1,...,2,4,3,4,0,4,2,19,10,12
50150,6060,18,21,21,2,4,7,2,0,0,...,0,2,1,4,0,0,0,24,6,5
50165,6060,18,243,210,39,32,65,10,0,16,...,0,3,4,9,9,9,9,12,31,27
50202,6060,18,24,22,3,6,5,0,0,0,...,5,7,4,0,4,3,2,9,17,19
50204,4040,13,1,1,0,0,0,0,0,0,...,0,0,0,0,0,1,2,7,1,2
50208,2020,6,2,2,0,0,0,0,0,0,...,0,0,1,0,2,0,0,3,1,2
50293,2020,6,19,15,2,1,3,0,0,0,...,0,0,3,0,0,0,0,9,3,5
50296,2020,6,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,2,0,1
50300,2020,5,37,35,3,4,4,0,0,1,...,0,0,2,0,0,2,0,7,5,5
50304,2020,6,1,1,0,1,0,0,0,0,...,0,0,0,1,0,0,0,5,1,0
50357,2020,7,11,11,0,0,3,1,0,0,...,0,0,1,0,2,0,0,2,1,3
50458,6060,18,110,98,8,21,24,2,1,0,...,8,8,5,4,6,0,8,19,32,25
50468,6060,18,163,132,27,26,37,8,0,6,...,6,3,6,6,3,0,5,9,24,20
50506,6060,18,250,223,36,29,63,12,1,4,...,6,0,3,8,5,9,6,16,29,33
50600,2020,7,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,1,3,2,0
50704,2020,7,20,19,0,1,5,2,0,0,...,3,0,0,0,1,0,0,7,1,6
50707,4040,13,40,38,4,1,9,0,0,0,...,0,4,0,1,0,2,0,10,4,8
50709,4040,13,20,19,2,1,5,0,0,0,...,3,4,0,2,1,0,0,14,6,8
50730,2020,7,8,8,1,0,4,3,0,0,...,2,0,0,0,0,0,0,4,0,2
50819,4040,13,5,4,0,0,1,0,0,0,...,0,0,1,2,0,0,0,14,3,0
50840,2020,7,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,8,1,0
50854,6060,18,194,175,8,22,49,5,1,1,...,6,3,6,8,0,6,6,5,26,23
50923,6060,18,248,225,59,48,67,8,5,17,...,4,3,0,9,9,6,9,15,32,31
60288,4040,11,60,55,5,4,12,1,0,0,...,3,3,4,5,2,0,1,16,15,16
60339,4040,11,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,1,13,1,2
60343,6060,18,52,46,7,5,9,0,0,2,...,3,2,3,0,4,0,3,24,10,12
60523,6060,18,155,138,21,26,44,9,0,4,...,3,0,3,4,5,6,2,8,16,18
60558,6060,18,55,50,5,7,11,1,1,0,...,6,3,8,3,0,4,5,11,18,20
60566,6060,18,34,32,0,10,4,0,0,0,...,4,3,0,6,6,4,3,12,18,23
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
78217,6060,18,48,47,7,11,14,0,1,0,...,0,5,4,4,8,8,7,14,26,23
78224,6060,18,282,236,57,41,66,9,0,11,...,9,8,8,0,9,6,3,12,28,35
78288,6060,18,176,157,12,13,40,9,0,2,...,8,7,8,6,9,3,6,24,27,30
78361,2020,6,6,5,0,0,1,0,0,0,...,0,1,0,0,1,0,2,2,3,1
78513,6060,18,276,252,37,44,71,15,0,13,...,6,0,3,8,5,9,6,7,28,33
78536,2020,6,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,8,0,1
78548,6060,18,204,177,39,19,50,7,0,6,...,6,9,7,5,3,6,6,24,31,29
78603,6060,18,157,135,18,20,51,12,0,0,...,3,6,3,5,3,3,6,5,17,21
78629,6060,18,243,210,40,34,60,10,0,9,...,3,6,5,8,6,8,9,13,30,29
78643,6060,18,76,64,9,10,17,3,0,4,...,1,2,1,4,4,4,6,25,13,14
78756,6060,18,103,94,12,7,22,3,0,2,...,3,5,0,3,4,2,3,18,14,17
78813,6060,18,64,62,4,2,17,4,0,1,...,3,2,0,3,2,3,5,18,12,15
78819,2020,7,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,3,1,0
79109,6060,18,246,219,31,37,60,12,3,7,...,0,5,4,9,8,9,9,13,33,29
79113,2020,5,6,6,0,1,1,0,0,0,...,2,0,0,2,3,1,3,5,7,8
79140,2020,5,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,2,1,0
79150,6060,18,126,114,14,18,28,6,1,3,...,0,6,4,8,9,8,7,25,32,24
79192,6060,18,218,197,29,31,51,8,1,5,...,0,5,4,9,6,9,5,11,29,24
79215,6060,18,257,226,34,52,73,20,0,6,...,9,8,7,0,8,6,2,3,27,32
79231,6060,18,229,206,22,33,55,7,4,2,...,8,8,9,0,9,6,3,26,28,33
79240,6060,18,193,176,26,27,67,7,1,4,...,6,7,6,0,9,3,3,15,23,23
79290,4040,13,65,59,13,7,13,1,0,2,...,3,1,3,0,5,3,3,18,11,13
79293,2020,6,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,8,0,1
79334,4040,11,37,31,2,1,4,0,0,0,...,0,1,0,3,0,2,3,12,4,7
79365,6060,18,212,188,38,29,54,15,0,10,...,9,4,8,3,6,8,0,15,28,29
79402,6060,18,262,219,20,42,73,15,1,1,...,9,9,6,6,6,0,9,3,35,27
79456,6060,18,157,140,22,14,45,6,1,0,...,8,6,7,3,7,7,0,16,25,25
79545,2020,6,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,8,0,1
79608,6060,18,247,221,26,23,61,16,0,4,...,6,0,3,8,5,9,4,15,29,31
79705,4040,11,25,18,1,1,3,1,0,0,...,1,2,3,0,2,0,4,13,9,6

In [14]:
df2['inplay_ratio'] = (df2['AB']-df2['KK']-df2['HR']-df2['SF'])/df2['PA']

In [15]:
babip = pd.read_csv("C:/Users/njj06/Desktop/batter_Total_BABIP.csv")

In [16]:
babip = babip[['P_ID', 'BABIP']]

In [17]:
babip = babip.drop_duplicates()

In [18]:
babip

       P_ID     BABIP
0     60404  0.142857
1     60667  0.380952
2     60757  0.000000
3     60805  0.260870
4     61700  0.309133
5     62700  0.344199
6     62797  0.299555
7     64086  0.302703
8     66740  0.330567
9     71347  0.319202
10    71610  0.309179
11    71752  0.372333
12    73136  0.332332
13    73602  0.267123
14    73750  0.000000
15    74163  0.335582
16    74729  0.330357
17    74731  0.000000
18    74857  0.000000
19    75808  0.322045
20    76746  0.373913
21    76753  0.343940
22    77243  0.265193
23    78745  0.000000
24    78756  0.282828
25    95158  0.343750
26    98144  0.206897
27    99737  0.000000
28    61643  0.000000
29    61666  0.000000
...     ...       ...
6485  68305  0.333333
6487  69360  0.000000
6488  69399  0.000000
6494  50707  0.333333
6495  50709  0.416667
6543  50054  0.315789
6567  61145  0.000000
6574  66113  0.290909
6576  68106  0.200000
6601  64565  0.000000
6639  50204  0.000000
6640  50208  0.000000
6641  50293  0.230769
6642  50296  0.000000
6651  68200  0.000000
6652  68204  0.290323
6665  50819  0.500000
6710  50304  0.000000
6711  61268  0.000000
6726  68346  0.400000
6734  50704  0.357143
6737  50730  0.571429
6756  50600  0.000000
6792  75342  0.000000
6800  62146  0.000000
6816  78819  0.000000
6872  50840  0.000000
6882  63894  0.000000
6917  50357  0.500000
6928  68341  0.000000

[707 rows x 2 columns]

In [19]:
babip = babip.groupby('P_ID').sum().loc[id,:]

In [20]:
babip

          BABIP
P_ID
50054  0.315789
50066  0.277778
50150  0.411765
50165  0.357664
50202  0.263158
50204  0.000000
50208  0.000000
50293  0.230769
50296  0.000000
50300  0.120000
50304  0.000000
50357  0.500000
50458  0.275862
50468  0.360465
50506  0.305699
50600  0.000000
50704  0.357143
50707  0.333333
50709  0.416667
50730  0.571429
50819  0.500000
50840  0.000000
50854  0.326531
50923  0.357143
60288  0.319149
60339  0.000000
60343  0.262357
60523  0.331108
60558  0.325221
60566  0.306626
...         ...
78217  0.345291
78224  0.358676
78288  0.312567
78361  0.342391
78513  0.328803
78536  0.363636
78548  0.296943
78603  0.349398
78629  0.311445
78643  0.283333
78756  0.282828
78813  0.327290
78819  0.000000
79109  0.336415
79113  0.298343
79140  0.000000
79150  0.302872
79192  0.343150
79215  0.362165
79231  0.306897
79240  0.317086
79290  0.302326
79293  0.000000
79334  0.288396
79365  0.302136
79402  0.313270
79456  0.316823
79545  0.000000
79608  0.331140
79705  0.285106

[299 rows x 1 columns]

In [21]:
df1['inplay_H'] = babip['BABIP']*((df2['AB']-df2['KK']-df2['HR']-df2['SF']) + df1['PA']*df2['inplay_ratio']) - (df2['HIT']-df2['HR'])

In [22]:
df1 = df1.fillna(0)

In [23]:
df1.inplay_H[df1.inplay_H < 0.0 ]=0

C:\Users\njj06\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [24]:
df1 = df1.round(0)

In [26]:
df1['inplay_H'] = df1['inplay_H'].astype('int')

In [27]:
df1

                   PA  inplay_H
P_ID  year month
50054 2020 7        7         2
           8       27         6
           9       32         7
           10      29         7
50066 2020 7        0         0
           8        0         0
           9        0         0
           10       0         0
50150 2020 7        8         3
           8       13         4
           9       14         5
           10      11         4
50165 2020 7       60         9
           8       93        15
           9       95        15
           10      77        12
50202 2020 7        4         0
           8        4         0
           9        1         0
           10       1         0
50204 2020 7        0         0
           8        1         0
           9        1         0
           10       1         0
50208 2020 7        1         0
           8        2         0
           9        2         0
           10       2         0
50293 2020 7        5         1
           8       19         3
...               ...       ...
79293 2020 9        0         0
           10       0         0
79334 2020 7        1         3
           8        3         3
           9        3         3
           10       3         3
79365 2020 7       50         9
           8       90        18
           9       91        18
           10      61        12
79402 2020 7       54         0
           8      111        10
           9      105         9
           10      82         4
79456 2020 7       40         4
           8       63         9
           9       58         8
           10      39         3
79545 2020 7        0         0
           8        0         0
           9        0         0
           10       0         0
79608 2020 7       46        16
           8       86        26
           9       92        28
           10      82        25
79705 2020 7        0         0
           8        1         0
           9        2         0
           10       1         0

[1172 rows x 2 columns]

In [28]:
df1.to_csv("predicted_inplay_hit.csv")